#===============
# SOURCE ACR
#===============

# definicao de imagem/mapa de atividade
# Mono energetic source
#/gate/source/addSource                                            ActivityImage voxel
#/gate/source/ActivityImage/reader/insert                          image
#/gate/source/ActivityImage/imageReader/translator/insert          range
#/gate/source/ActivityImage/imageReader/rangeTranslator/readTable  ICRP/data/activity_ranges/ActivityRange152.dat
#/gate/source/ActivityImage/imageReader/rangeTranslator/describe   1
#/gate/source/ActivityImage/imageReader/readFile                   ICRP/data/AM_UINT16_254_127_222.mhd
#/gate/source/ActivityImage/setPosition                            -271.399 -135.6995 -888.0 mm


/gate/source/addSource Ra223_ACR gps
/gate/source/Ra223_ACR/gps/particle ion
/gate/source/Ra223_ACR/gps/ion 88 223 0 0

#/gate/source/Ra223_ACR/setActivity 86400 becquerel
/gate/source/Ra223_ACR/setActivity 17.91 becquerel

/gate/source/Ra223_ACR/gps/type Volume
/gate/source/Ra223_ACR/gps/shape Cylinder
/gate/source/Ra223_ACR/gps/radius 10.78 cm
/gate/source/Ra223_ACR/gps/halfz 9.3 cm

/gate/source/Ra223_ACR/setForcedUnstableFlag true
/gate/source/Ra223_ACR/useDefaultHalfLife
/gate/source/Ra223_ACR/gps/monoenergy 0. keV 
/gate/source/Ra223_ACR/gps/angtype iso
/gate/source/Ra223_ACR/gps/confine NULL  

/gate/source/Ra223_ACR/attachTo ACR1
/gate/source/Ra223_ACR/visualize 5000 red 2


#===============
# SOURCE Cylinder content 1
#===============

/gate/source/addSource Ra223_cylinder1 gps
/gate/source/Ra223_cylinder1/gps/particle ion
/gate/source/Ra223_cylinder1/gps/ion 88 223 0 0

#/gate/source/Ra223_cylinder1/setActivity 16280 becquerel  #Ains
#/gate/source/Ra223_cylinder1/setActivity 4620 becquerel  #Adet
/gate/source/Ra223_cylinder1/setActivity 15620 becquerel

/gate/source/Ra223_cylinder1/gps/type Volume
/gate/source/Ra223_cylinder1/gps/shape Cylinder
/gate/source/Ra223_cylinder1/gps/radius 4.0 mm
/gate/source/Ra223_cylinder1/gps/halfz 1.99 cm

/gate/source/Ra223_cylinder1/setForcedUnstableFlag true
/gate/source/Ra223_cylinder1/useDefaultHalfLife
/gate/source/Ra223_cylinder1/gps/monoenergy 0. keV 
/gate/source/Ra223_cylinder1/gps/angtype iso
/gate/source/Ra223_cylinder1/gps/confine NULL  

/gate/source/Ra223_cylinder1/attachTo c1content
/gate/source/Ra223_cylinder1/visualize 5000 red 2



#===============
# SOURCE Cylinder content 2
#===============

/gate/source/addSource Ra223_cylinder2 gps
/gate/source/Ra223_cylinder2/gps/particle ion
/gate/source/Ra223_cylinder2/gps/ion 88 223 0 0

#/gate/source/Ra223_cylinder1/setActivity 36632 becquerel  #Ains
#/gate/source/Ra223_cylinder2/setActivity 20019 becquerel  #Adet
/gate/source/Ra223_cylinder2/setActivity 35795 becquerel

/gate/source/Ra223_cylinder2/gps/type Volume
/gate/source/Ra223_cylinder2/gps/shape Cylinder
/gate/source/Ra223_cylinder2/gps/radius 6.00 mm
/gate/source/Ra223_cylinder2/gps/halfz 1.99 cm

/gate/source/Ra223_cylinder2/setForcedUnstableFlag true
/gate/source/Ra223_cylinder2/useDefaultHalfLife
/gate/source/Ra223_cylinder2/gps/monoenergy 0. keV 
/gate/source/Ra223_cylinder2/gps/angtype iso
/gate/source/Ra223_cylinder2/gps/confine NULL  


/gate/source/Ra223_cylinder2/attachTo c2content
/gate/source/Ra223_cylinder2/visualize 5000 red 2

#===============
# SOURCE Cylinder content 3
#===============

/gate/source/addSource Ra223_cylinder3 gps
/gate/source/Ra223_cylinder3/gps/particle ion
/gate/source/Ra223_cylinder3/gps/ion 88 223 0 0

#/gate/source/Ra223_cylinder1/setActivity 65121 becquerel  #Ains
#/gate/source/Ra223_cylinder3/setActivity 64570 becquerel  #Adet
/gate/source/Ra223_cylinder3/setActivity 64840 becquerel


/gate/source/Ra223_cylinder3/gps/type Volume
/gate/source/Ra223_cylinder3/gps/shape Cylinder
/gate/source/Ra223_cylinder3/gps/radius 8.0 mm
/gate/source/Ra223_cylinder3/gps/halfz 1.99 cm

/gate/source/Ra223_cylinder3/setForcedUnstableFlag true
/gate/source/Ra223_cylinder3/useDefaultHalfLife
/gate/source/Ra223_cylinder3/gps/monoenergy 0. keV 
/gate/source/Ra223_cylinder3/gps/angtype iso
/gate/source/Ra223_cylinder3/gps/confine NULL  


/gate/source/Ra223_cylinder3/attachTo c3content
/gate/source/Ra223_cylinder3/visualize 5000 red 2

#===============
# SOURCE Cylinder content 4
#===============

/gate/source/addSource Ra223_cylinder4 gps
/gate/source/Ra223_cylinder4/gps/particle ion
/gate/source/Ra223_cylinder4/gps/ion 88 223 0 0

#/gate/source/Ra223_cylinder1/setActivity 154665 becquerel  #Ains
#/gate/source/Ra223_cylinder4/setActivity 165543 becquerel  #Adet
/gate/source/Ra223_cylinder4/setActivity 152643 becquerel


/gate/source/Ra223_cylinder4/gps/type Volume
/gate/source/Ra223_cylinder4/gps/shape Cylinder
/gate/source/Ra223_cylinder4/gps/radius 12.5 mm
/gate/source/Ra223_cylinder4/gps/halfz 1.99 cm

/gate/source/Ra223_cylinder4/setForcedUnstableFlag true
/gate/source/Ra223_cylinder4/useDefaultHalfLife
/gate/source/Ra223_cylinder4/gps/monoenergy 0. keV 
/gate/source/Ra223_cylinder4/gps/angtype iso
/gate/source/Ra223_cylinder4/gps/confine NULL  


/gate/source/Ra223_cylinder4/attachTo c4content
/gate/source/Ra223_cylinder4/visualize 5000 red 2



